name: Deploy DEMO Next.js App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    
    defaults:
      run:
        working-directory: D:\sites\demo-deploy
        shell: powershell
    
    steps:
    # - name: Debug user and PM2 access
    #   run: |
    #     whoami
    #     echo "---PM2 List---"
    #     pm2 list
    #     echo "---Node Processes---"
    #     Get-Process -Name "node" -IncludeUserName -ErrorAction SilentlyContinue | Select-Object UserName, Id, ProcessName

    # - name: Stop PM2 app
    #   run: pm2 stop deployment
    #   continue-on-error: true

    - name: Pull latest changes
      run: git pull origin main
    
    - name: Delete old build
      run: rm -Recurse -Force .next
    
    # - name: Stop application
    #   run: |
    #     pm2 stop deployment
    #     Start-Sleep -Seconds 3
    #   continue-on-error: true 
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: npm run build
      env:
        NODE_ENV: production
    
    # - name: Restart application
    #   run: |
    #     pm2 restart deployment
    #     pm2 save
    
    # - name: Show application status
    #   run: pm2 list