name: Deploy DEMO Next.js App

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    
    defaults:
      run:
        working-directory: D:\sites\demo-deploy  # Set this once
        shell: powershell
    
    steps:
    - name: Pull latest changes
      run: git pull origin main
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: npm run build
      env:
        NODE_ENV: production
    
    - name: Restart application
      run: pm2 restart deployment  # or your restart method